name: Build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install depends
              run: |
                  sudo apt-get update
                  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gcc make git ninja-build

            - name: Build and install GraphBLAS
              run: |
                  git clone https://github.com/DrTimothyAldenDavis/GraphBLAS.git
                  cd GraphBLAS
                  CMAKE_OPTIONS="-G Ninja" make compact
                  sudo make install
                  cd ..

            - name: Build and install LAGraph benchmark branch
              run: |
                  git clone https://github.com/SparseLinearAlgebra/LAGraph.git
                  cd LAGraph
                  git switch homka122/all_algorithms_benchmark
                  make
                  sudo make install
                  cd ..

            - name: Build benchmark
              run: |
                  make bench-CI

            - name: Run benchmark
              run: |
                  export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
                  ./build/test -efblt -c configs/configs_my.csv -a CFL_adv -r 3 --hot
